/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmiCalculatorRouteImport } from './routes/emi-calculator'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HomeLoansRouteImport } from './routes/home-loans'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoanAgainstPropertyRouteImport } from './routes/loan-against-property'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LocationRouteImport } from './routes/location'
import { Route as OtherLoansRouteImport } from './routes/other-loans'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PropertyTypesRouteImport } from './routes/property-types'
import { Route as RealAssetsRouteImport } from './routes/real-assets'
import { Route as RealEstateInvestmentRouteImport } from './routes/real-estate-investment'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiCalculatorRoute = EmiCalculatorRouteImport.update({
  id: '/emi-calculator',
  path: '/emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLoansRoute = HomeLoansRouteImport.update({
  id: '/home-loans',
  path: '/home-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanAgainstPropertyRoute = LoanAgainstPropertyRouteImport.update({
  id: '/loan-against-property',
  path: '/loan-against-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherLoansRoute = OtherLoansRouteImport.update({
  id: '/other-loans',
  path: '/other-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyTypesRoute = PropertyTypesRouteImport.update({
  id: '/property-types',
  path: '/property-types',
  getParentRoute: () => rootRouteImport,
} as any)
const RealAssetsRoute = RealAssetsRouteImport.update({
  id: '/real-assets',
  path: '/real-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateInvestmentRoute = RealEstateInvestmentRouteImport.update({
  id: '/real-estate-investment',
  path: '/real-estate-investment',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faq': typeof FaqRoute
  '/home-loans': typeof HomeLoansRoute
  '/insights': typeof InsightsRouteWithChildren
  '/loan-against-property': typeof LoanAgainstPropertyRoute
  '/loans': typeof LoansRoute
  '/location': typeof LocationRoute
  '/other-loans': typeof OtherLoansRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-types': typeof PropertyTypesRoute
  '/real-assets': typeof RealAssetsRoute
  '/real-estate-investment': typeof RealEstateInvestmentRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faq': typeof FaqRoute
  '/home-loans': typeof HomeLoansRoute
  '/insights': typeof InsightsRouteWithChildren
  '/loan-against-property': typeof LoanAgainstPropertyRoute
  '/loans': typeof LoansRoute
  '/location': typeof LocationRoute
  '/other-loans': typeof OtherLoansRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-types': typeof PropertyTypesRoute
  '/real-assets': typeof RealAssetsRoute
  '/real-estate-investment': typeof RealEstateInvestmentRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faq': typeof FaqRoute
  '/home-loans': typeof HomeLoansRoute
  '/insights': typeof InsightsRouteWithChildren
  '/loan-against-property': typeof LoanAgainstPropertyRoute
  '/loans': typeof LoansRoute
  '/location': typeof LocationRoute
  '/other-loans': typeof OtherLoansRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-types': typeof PropertyTypesRoute
  '/real-assets': typeof RealAssetsRoute
  '/real-estate-investment': typeof RealEstateInvestmentRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/careers'
    | '/contact'
    | '/emi-calculator'
    | '/faq'
    | '/home-loans'
    | '/insights'
    | '/loan-against-property'
    | '/loans'
    | '/location'
    | '/other-loans'
    | '/partners'
    | '/privacy-policy'
    | '/property-types'
    | '/real-assets'
    | '/real-estate-investment'
    | '/services'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/insights/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/careers'
    | '/contact'
    | '/emi-calculator'
    | '/faq'
    | '/home-loans'
    | '/insights'
    | '/loan-against-property'
    | '/loans'
    | '/location'
    | '/other-loans'
    | '/partners'
    | '/privacy-policy'
    | '/property-types'
    | '/real-assets'
    | '/real-estate-investment'
    | '/services'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/insights/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/careers'
    | '/contact'
    | '/emi-calculator'
    | '/faq'
    | '/home-loans'
    | '/insights'
    | '/loan-against-property'
    | '/loans'
    | '/location'
    | '/other-loans'
    | '/partners'
    | '/privacy-policy'
    | '/property-types'
    | '/real-assets'
    | '/real-estate-investment'
    | '/services'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/insights/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EmiCalculatorRoute: typeof EmiCalculatorRoute
  FaqRoute: typeof FaqRoute
  HomeLoansRoute: typeof HomeLoansRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  LoanAgainstPropertyRoute: typeof LoanAgainstPropertyRoute
  LoansRoute: typeof LoansRoute
  LocationRoute: typeof LocationRoute
  OtherLoansRoute: typeof OtherLoansRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertyTypesRoute: typeof PropertyTypesRoute
  RealAssetsRoute: typeof RealAssetsRoute
  RealEstateInvestmentRoute: typeof RealEstateInvestmentRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi-calculator': {
      id: '/emi-calculator'
      path: '/emi-calculator'
      fullPath: '/emi-calculator'
      preLoaderRoute: typeof EmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-loans': {
      id: '/home-loans'
      path: '/home-loans'
      fullPath: '/home-loans'
      preLoaderRoute: typeof HomeLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-against-property': {
      id: '/loan-against-property'
      path: '/loan-against-property'
      fullPath: '/loan-against-property'
      preLoaderRoute: typeof LoanAgainstPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-loans': {
      id: '/other-loans'
      path: '/other-loans'
      fullPath: '/other-loans'
      preLoaderRoute: typeof OtherLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-types': {
      id: '/property-types'
      path: '/property-types'
      fullPath: '/property-types'
      preLoaderRoute: typeof PropertyTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-assets': {
      id: '/real-assets'
      path: '/real-assets'
      fullPath: '/real-assets'
      preLoaderRoute: typeof RealAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate-investment': {
      id: '/real-estate-investment'
      path: '/real-estate-investment'
      fullPath: '/real-estate-investment'
      preLoaderRoute: typeof RealEstateInvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EmiCalculatorRoute: EmiCalculatorRoute,
  FaqRoute: FaqRoute,
  HomeLoansRoute: HomeLoansRoute,
  InsightsRoute: InsightsRouteWithChildren,
  LoanAgainstPropertyRoute: LoanAgainstPropertyRoute,
  LoansRoute: LoansRoute,
  LocationRoute: LocationRoute,
  OtherLoansRoute: OtherLoansRoute,
  PartnersRoute: PartnersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertyTypesRoute: PropertyTypesRoute,
  RealAssetsRoute: RealAssetsRoute,
  RealEstateInvestmentRoute: RealEstateInvestmentRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
